default:
  tags:
    - docker
  image: sergiud/conics

build:
  stage: build
  script:
    - make -C docs/ html

test:
  stage: test
  script:
    - coverage run --source=conics/
      -m pytest
      --junitxml pytest.xml
    - coverage report
    - coverage xml
  needs: []
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: pytest.xml
